"""empty message

Revision ID: 01a0d4da69cd
Revises: c7790f609f78
Create Date: 2022-06-03 17:23:47.943741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a0d4da69cd'
down_revision = 'c7790f609f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('tracklist', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('year', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Album')
    # ### end Alembic commands ###
