"""empty message

Revision ID: 1a3e72347f3b
Revises: d59a4c34c12c
Create Date: 2022-06-03 17:52:12.491533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3e72347f3b'
down_revision = 'd59a4c34c12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Album', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Album', 'year')
    # ### end Alembic commands ###
