"""empty message

Revision ID: e2e18e5e704b
Revises: 01a0d4da69cd
Create Date: 2022-06-03 17:41:07.040452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e18e5e704b'
down_revision = '01a0d4da69cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Album', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Album', 'image_link')
    # ### end Alembic commands ###
